# Markdown'u Tanıma

# Hücre içi kısa yollar:

- CTRL + C: kopyala
- CTRL + V: yapıştır
- CTRL + X: kes

# Hücre dışı kısa yollar:

- C: kopyala
- V: yapıştır
- X: kes


## Alt başlık

### Daha alt başlık

h<sub>&theta;</sub>(x) = &theta;<sub>o</sub> x + &theta;<sub>1</sub>x

# Neden Numpy?

In [5]:
a = [1,2,3,4]
b = [2,3,4,5]

In [6]:
len(a)

4

In [9]:
b[0]

2

In [14]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i] * b[i])
    
ab    

[2, 6, 12, 20]

In [11]:
import numpy as np

In [17]:
?np.array

Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
    If

In [15]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [16]:
type(a)

numpy.ndarray

In [18]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [21]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [23]:
?np.random.normal

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the ``normal`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int or tuple of ints, optional
    Output shape.  If t

In [22]:
np.random.normal(10, 4, (3,4))

array([[12.67849045, 12.97005625, 15.67691983, 18.66405187],
       [ 8.16939291, 10.51029668,  7.03578088,  1.22739942],
       [10.25178495, 12.61964207, 18.67888419,  3.75616666]])

- ndim: boyut sayısı
- shape: boyut bilgisi
- size: toplam eleman sayısı
- dtype: array veri tipi

In [24]:
a = np.arange(0,31, 3)

In [25]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [26]:
a.ndim

1

In [27]:
a.shape

(11,)

In [28]:
a.size

11

In [29]:
a.dtype

dtype('int64')

In [31]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [34]:
#index
a[6]

18

In [35]:
#slice
a[6:9]

array([18, 21, 24])

In [36]:
a = np.random.normal(10, 4, (3,4))

In [38]:
a[0,0]

13.123264047904009

In [39]:
a

array([[13.12326405,  9.58574305,  8.74269002,  8.18058668],
       [10.31687624, 11.08969551, 15.89704834,  8.15647683],
       [10.82805525, 10.60806512, 19.64600835, 16.88091036]])

In [40]:
a[2, 3]

16.88091035850624

In [41]:
a[2, 3] = 18.98

In [42]:
a

array([[13.12326405,  9.58574305,  8.74269002,  8.18058668],
       [10.31687624, 11.08969551, 15.89704834,  8.15647683],
       [10.82805525, 10.60806512, 19.64600835, 18.98      ]])

In [43]:
a[2, 3] = 99

In [44]:
a

array([[13.12326405,  9.58574305,  8.74269002,  8.18058668],
       [10.31687624, 11.08969551, 15.89704834,  8.15647683],
       [10.82805525, 10.60806512, 19.64600835, 99.        ]])

In [46]:
a[:,0]

array([13.12326405, 10.31687624, 10.82805525])

In [47]:
a[:,1]

array([ 9.58574305, 11.08969551, 10.60806512])

In [48]:
a[0:2, 0:3]

array([[13.12326405,  9.58574305,  8.74269002],
       [10.31687624, 11.08969551, 15.89704834]])

In [49]:
a

array([[13.12326405,  9.58574305,  8.74269002,  8.18058668],
       [10.31687624, 11.08969551, 15.89704834,  8.15647683],
       [10.82805525, 10.60806512, 19.64600835, 99.        ]])

In [50]:
#index
#slice
#fancy index
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [51]:
v[1]

3

In [52]:
v[3]

9

In [53]:
v[8]

24

In [56]:
al_getir = [1, 3, 8]

In [57]:
v[al_getir]

array([ 3,  9, 24])

# Koşullu Eleman İşlemleri

In [58]:
v = np.array([1, 2, 3, 4, 5])

In [62]:
v < 3

array([ True,  True, False, False, False])

In [63]:
v[v < 3]

array([1, 2])

In [64]:
v[v > 3]

array([4, 5])

In [65]:
v[v >= 3]

array([3, 4, 5])

In [66]:
v * 2

array([ 2,  4,  6,  8, 10])

In [67]:
v ** 2

array([ 1,  4,  9, 16, 25])

# Pandas

## Pandas DataFrame

In [68]:
import pandas as pd 

In [71]:
l = [1,2,3,4,10]

In [72]:
type(l)

list

In [74]:
?pd.DataFrame

Init signature:
pd.DataFrame(
    data=None,
    index: Union[Collection, NoneType] = None,
    columns: Union[Collection, NoneType] = None,
    dtype: Union[str, numpy.dtype, ForwardRef('ExtensionDtype'), NoneType] = None,
    copy: bool = False,
)
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, or list-like objects.

    .. versionchanged:: 0.23.0
       If data is a dict, column order follows insertion-order for
       Python 3.6 and later.

    .. versionchanged:: 0.25.0
       If data is a list of dicts, column order follows insertion-order
       for Python 3.6 and later.

index : Ind

In [75]:
pd.DataFrame(l, columns = ["Degisken_ismi"])

Degisken_ismi
0              1
1              2
2              3
3              4
4             10

In [76]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
df = pd.DataFrame(m, columns = ["VAR1","VAR2","VAR3"])

In [80]:
df

VAR1  VAR2  VAR3
0     1     2     3
1     4     5     6
2     7     8     9

In [81]:
df.columns

Index(['VAR1', 'VAR2', 'VAR3'], dtype='object')

In [92]:
type(("deg1","deg2","deg3"))

tuple

In [82]:
df.columns = ("deg1","deg2","deg3")

In [83]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [84]:
df.shape

(3, 3)

In [85]:
df.ndim

2

In [86]:
df.size

9

In [87]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [90]:
type(df.values)

numpy.ndarray

In [93]:
?np.random.randint

Docstring:
randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k

In [98]:
# Eleman İşlemleri

import numpy as np
s1 = np.random.randint(0,10, size = 5)
s2 = np.random.randint(0,10, size = 5)
s3 = np.random.randint(0,10, size = 5)

In [99]:
sozluk = {"var1":s1, "var2":s2, "var3":s3}

In [100]:
type(sozluk)

dict

In [101]:
pd.DataFrame(sozluk)

var1  var2  var3
0     4     9     3
1     9     7     8
2     4     2     2
3     8     7     6
4     8     4     4

In [105]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [103]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [104]:
df.columns

Index(['deg1', 'deg2', 'deg3'], dtype='object')

In [106]:
df.index = ["a","b","c"]

In [107]:
df

deg1  deg2  deg3
a     1     2     3
b     4     5     6
c     7     8     9

In [109]:
?df.drop

Signature:
df.drop(
    labels=None,
    axis=0,
    index=None,
    columns=None,
    level=None,
    inplace=False,
    errors='raise',
)
Docstring:
Drop specified labels from rows or columns.

Remove rows or columns by specifying label names and corresponding
axis, or by specifying directly index or column names. When using a
multi-index, labels on different levels can be removed by specifying
the level.

Parameters
----------
labels : single label or list-like
    Index or column labels to drop.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Whether to drop labels from the index (0 or 'index') or
    columns (1 or 'columns').
index : single label or list-like
    Alternative to specifying axis (``labels, axis=0``
    is equivalent to ``index=labels``).

    .. versionadded:: 0.21.0
columns : single label or list-like
    Alternative to specifying axis (``labels, axis=1``
    is equivalent to ``columns=labels``).

    .. versionadded:: 0.21.0
level : int or level name, optiona

In [108]:
df.drop("a", axis = 0)

deg1  deg2  deg3
b     4     5     6
c     7     8     9

In [110]:
df.drop("deg1", axis = 1)

deg2  deg3
a     2     3
b     5     6
c     8     9